#!/bin/bash

################################################################################
#
# File:    $FILE
# Project: OpenSonATA
# Authors: The OpenSonATA code is the result of many programmers
#          over many years
#
# Copyright 2011 The SETI Institute
#
# OpenSonATA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# OpenSonATA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with OpenSonATA.  If not, see<http://www.gnu.org/licenses/>.
# 
# Implementers of this code are requested to include the caption
# "Licensed through SETI" with a link to setiQuest.org.
# 
# For alternate licensing arrangements, please contact
# The SETI Institute at www.seti.org or setiquest.org. 
#
################################################################################

# This script attempts to automatically download and install all the necessary 
# software libraries needed for building and executing the SonATA software.
# The software installs into the ~/opensonata_packages directory, so after
# this is complete you have to add to your path, see the echoed statements
# at the end.
# 
# This script is 95% complete. What is missing is testing to see if it works
# properly. I ran out of time and was not able to test this thoroughly. If we
# can get this working it will make the installation on a fresh system much 
# easier. - Jon Richards - Feb 03/2011
####################################################################################

mkdir ~/opensonata_packages
mkdir ~/opensonata_packages/downloads
mkdir ~/opensonata_packages/installs
mkdir ~/opensonata_packages/build

####################################
#Download and install GMP 4.3.2
####################################
cd ~/opensonata_packages/downloads
wget ftp://ftp.gnu.org/gnu/gmp/gmp-4.3.2.tar.gz
gzip -d gmp-4.3.2.tar.gz
tar -xvf gmp-4.3.2.tar       
cd gmp-4.3.2/
./configure --prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/gmp*

####################################
#Download and install MPFR-2.4.2.tar.gz
####################################
cd ~/opensonata_packages/downloads
wget www.mpfr.org/mpfr-current/mpfr-2.4.2.tar.gz
gzip -d mpfr-2.4.2.tar.gz
tar -xvf mpfr-2.4.2.tar
cd mpfr-2.4.2
./configure --prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/mpfr*

export LD_LIBRARY_PATH=~/opensonata_packages/install/lib:$LD_LIBRARY_PATH
export PATH=~/opensonata_packages/install/bin:$PATH

####################################
#Download and install GCC 4.23.3
####################################
cd ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/gcc/gcc-4.3.3/gcc-4.3.3.tar.gz
gunzip gcc-4.3.3.tar.gz
tar -xvf gcc-4.3.3.tar
mkdir ~/opensonata_packages/build
cd ~/opensonata_packages/build
setenv CFLAGS -m64
$HOME/opensonata_packages/downloads/gcc-4.3.3/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs --with-gmp=$HOME/opensonata_packages/installs --with-mpfr=$HOME/opensonata_packages/installs --enable-threads --enable-languages=c,c++ --disable-multilib
make
make check
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/gcc-4.3.3*


####################################
#Download and install automake 1.8.4
####################################
cd  ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/automake/automake-1.8.4.tar.gz
gunzip automake-1.8.4.tar.gz
tar -xvf automake-1.8.4.tar
cd automake-1.8.4
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/automake-1.8.4/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/automake-1.8.4*

####################################
##Download and install autoconf 2.59
#####################################
cd  ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.59.tar.gz
gunzip autoconf-2.59.tar.gz
tar -xvf autoconf-2.59.tar
cd autoconf-2.59
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/autoconf-2.59/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/autoconf-2.59*

####################################
##Download and install libtool 1.5.6
#####################################
cd  ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/libtool/libtool-1.5.6.tar.gz
gunzip libtool-1.5.6.tar.gz
tar -xvf libtool-1.5.6.tar
cd libtool-1.5.6
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/libtool-1.5.6/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/libtool-1.5.6*

####################################
##Download and install libtool 2.2.6b
#####################################
cd  ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/libtool/libtool-2.2.6b.tar.gz
gunzip libtool-2.2.6b.tar.gz
tar -xvf libtool-2.2.6b.tar
cd libtool-2.2.6b
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/libtool-2.2.6b/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/libtool-2*




####################################
##Download and install m4 1.4
#####################################
cd  ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/m4/m4-1.4.tar.gz
gunzip m4-1.4.tar.gz
tar -xvf m4-1.4.tar
cd m4-1.4
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/m4-1.4/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/m4-1.4*

####################################
##Download JDK 1.5
#####################################
#cd  ~/opensonata_packages/downloads
#wget http://cds.sun.com/is-bin/INTERSHOP.enfinity/WFS/CDS-CDS_Developer-Site/en_US/-/USD/VerifyItem-Start/jdk-1_5_0_22-linux-amd64.bin?BundledLineItemUUID=ieaJ_hCvltYAAAEoHJgLLbJq&OrderID=uGqJ_hCveFAAAAEoAZgLLbJq&ProductID=jFFIBe.nZPIAAAEkug5UGl.X&FileName=/jdk-1_5_0_22-linux-amd64.bin

# mv jdk-1_5_0_22-linux-amd64.bin\?AuthParam\=1274303863_a9896f7f641af5e939c5dfecf2e21dd4\&TicketId\=B%2Fw7nBqISVxIShxBP1Rckwbr\&GroupName\=CDS\&FilePath\=%2FESD6%2FJSCDL%2Fjdk%2F1.5.0_22%2Fjdk-1_5_0_22-linux-amd64.bin\&File\=jdk-1_5_0_22-linux-amd64.bin  jdk-1_5_0_22-linux-amd64.bin
#chmod 755 jdk-1_5_0_22-linux-amd64.bin 
#./jdk-1_5_0_22-linux-amd64.bin
#mv jdk1.5.0_22 $HOME/opensonata_packages/installs
#rm -rf ~/opensonata_packages/downloads/java*

####################################
##Download TCL8.5.7
#####################################
cd  ~/opensonata_packages/downloads
wget http://prdownloads.sourceforge.net/tcl/tcl8.5.7-src.tar.gz
gunzip tcl8.5.7-src.tar.gz
tar -xvf tcl8.5.7-src.tar
cd tcl8.5.7
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/tcl8.5.7/unix/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
cp $HOME/opensonata_packages/downloads/tcl8.5.7/generic/tclInt.h $HOME/opensonata_packages/installs/include/
make 
make install

####################################
##Download Tk8.4.18
#####################################
cd  ~/opensonata_packages/downloads
wget http://prdownloads.sourceforge.net/tcl/tk8.5.8-src.tar.gz
gunzip tk8.5.8-src.tar.gz
tar -xvf tk8.5.8-src.tar
cd tk8.5.8
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/tk8.5.8/unix/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs --with-tcl=/home/opensonata/opensonata_packages/installs/lib
make 
make install

####################################
#Download SWIG 1.3.31
#####################################
cd  ~/opensonata_packages/downloads
wget http://prdownloads.sourceforge.net/swig/swig-1.3.31.tar.gz
gunzip swig-1.3.31.tar.gz
tar -xvf swig-1.3.31.tar
cd swig-1.3.31
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/swig-1.3.31/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make 
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/swig-1.3.31*

####################################
#Download Expect 5.4.1.15
#####################################
cd  ~/opensonata_packages/downloads
wget http://sourceforge.net/projects/expect/files/Expect/5.44.1.15/expect-5.44.1.15.tar.gz/download
gunzip expect-5.44.1.15.tar.gz
tar -xvf expect-5.44.1.15.tar
cd  expect-5.44.1.15
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/expect-5.44.1.15/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs --with-tclconfig=$HOME/opensonata_packages/installs/lib --with-tkconfig=$HOME/opensonata_packages/installs/lib -with-tclinclude=/home/opensonata/opensonata_packages/installs/include
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/expect-5.44.1.15*
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/tk8*
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/tcl8*


####################################
##Download and install gnu readline
#####################################
cd  ~/opensonata_packages/downloads
wget http://ftp.gnu.org/gnu/readline/readline-5.2.tar.gz
gunzip readline-5.2.tar.gz
tar -xvf readline-5.2.tar
cd  readline-5.2
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/readline-5.2/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/readline-5.2*

####################################
##Download and install  fftw
#####################################
cd  ~/opensonata_packages/downloads
wget http://www.fftw.org/fftw-3.2.1.tar.gz
gunzip fftw-3.2.1.tar.gz
tar -xvf fftw-3.2.1.tar
cd  fftw-3.2.1
cd ~/opensonata_packages/build
$HOME/opensonata_packages/downloads/fftw-3.2.1/configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs --enable-threads --enable-float --enable-sse --disable-fortran
make
make check
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/fftw-3.2.1*

#####################################
## Build and install ncurses
#####################################
cd  ~/opensonata_packages/downloads
wget ftp://ftp.gnu.org/gnu/ncurses/ncurses-5.7.tar.gz
gunzip ncurses-5.7.tar.gz
tar -xvf ncurses-5.7.tar
cd ncurses-5.7
./configure --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make
make install
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/nc*


####################################
##Download and install  ACE_wrappers
#####################################
cd  ~/opensonata_packages/downloads
wget http://download.dre.vanderbilt.edu/previous_versions/ACE-5.7.8.zip
unzip ACE-5.7.8.zip
cd ACE_wrappers
export ACE_ROOT=$PWD
cd $ACE_ROOT/ace
dos2unix ../bin/add_rel_link.sh
ln -s config-linux.h config.h
cd $ACE_ROOT/include/makeinclude
ln -s platform_linux.GNU platform_macros.GNU

cd $ACE_ROOT/ace
make
rm -rf $HOME/opensonata_packages/installs/ACE_wrappers
mkdir $HOME/opensonata_packages/installs/ACE_wrappers
cp -r $ACE_ROOT/* $HOME/opensonata_packages/installs/ACE_wrappers
rm -rf ~/opensonata_packages/build/*
rm -rf ~/opensonata_packages/downloads/A*

####################################
##Download and install xtail 
#####################################
cd  ~/opensonata_packages/downloads
wget http://www.unicom.com/files/xtail-2.1.tar.gz
gzip -d xtail-2.1.tar.gz
tar -xvf xtail-2.1.tar
cd ~/opensonata_packages/downloads/xtail-2.1
sh ./configure 
make
cp xtail ../../installs/bin
rm -rf ~/opensonata_packages/downloads/x*

####################################
## Build CppUnit
#####################################
cd  ~/opensonata_packages/opensonata/OpenSonATA
cd CppUnit
./reconfig --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
make check
make install

#####################################
## Build tclreadline
#####################################
cd  ~/opensonata_packages/opensonata/OpenSonATA/tclreadline
./reconfig --with-tcl=/usr/lib64 --with-tlib-library="-lncurses" --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs --with-tcl=$HOME/opensonata_packages/installs/lib --with-readline-includes=$HOME/opensonata_packages/installs/include/readline
make install

#####################################
## Build sse-pkg
#####################################
cd  ~/opensonata_packages/opensonata/OpenSonATA/sse-pkg

sed "s/ACE_ROOT=/XACE_ROOT=/g" ~/opensonata_packages/opensonata/OpenSonATA/sse-pkg/configure.in > ~/opensonata_packages/opensonata/OpenSonATA/sse-pkg/configure.in.tmp
mv configure.in.tmp configure.in 
chmod 755 ./configure.in
./reconfig
make
make install

#####################################
## Build sigproc-pkg
#####################################
cd  ~/opensonata_packages/opensonata/OpenSonATA/sigproc-pkg
ln -s  ~/opensonata_packages/opensonata/OpenSonATA/sigproc-pkg/libtool 
./reconfig --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
cd utilities
./reconfig --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
cd ../ATApackets
./reconfig --prefix=$HOME/opensonata_packages/installs --with-local-prefix=$HOME/opensonata_packages/installs
cd ..
make leastsquares
make
make install

sed "10ilappend ::auto_path ~/opensonata_packages/installs/lib" ~/opensonata_packages/opensonata/OpenSonATA/sse-pkg/util/example.sserc > ~/.sserc

clear

echo "###########################################################"
echo  Finished. Please put these changes into your .bashrc file.
echo "###########################################################"
echo 
echo export PATH=$JAVA_HOME/bin:~/opensonata_packages/installs/bin:$PATH
echo export ACE_ROOT=$HOME/opensonata_packages/installs/ACE_wrappers
echo export LD_LIBRARY_PATH=$ACE_ROOT/ace:$ACE_ROOT/lib:~/opensonata_packages/installs/lib:$JAVA_HOME/jre/lib:$LD_LIBRARY_PATH
echo
echo And you need to add this to your shell rc file:
echo "limit stacksize unlimited"
echo



echo ##############################################################
echo # You may wish to install mysql. Use
echo # zypper install mysql mysql-tools mysql-devel
echo #
echo # To start mysql become root then "/etc/init.d/mysql start"
echo #
echo ##############################################################
echo #
echo # To download java version http://java.sun.com/products/archive/
echo # and downlaod JDK/JRE 5.0,  jdk-1_5_0_22-linux-amd64.bin
echo # Execute  jdk-1_5_0_22-linux-amd64.bin which will create 
echo # a directory . Move this directory to
echo # ~/opensonata_packages/installs/jdk
echo #
echo ##############################################################
